osx_image: xcode7.2
language: objective-c
before_install:
  - carthage bootstrap --platform ios
script:
  - xctool -project PurchaseHelper.xcodeproj -scheme PurchaseHelper -sdk iphonesimulator clean build test

